file = open("bucket-list.txt", "w")
file.write("1. Vist the Effiel Tower\n")
file.write("2. Learn to play the guitar\n")
file.write("3. Code my own game\n")
file.close()
print("Bucket list saved to bucket-list.txt!")

file = open("bucket-list.txt", "r")
content = file.read()
print("\n=== My Bucket List ===")
print(content)
file.close()

file = open("bucket-list.txt", "r")
lines = file.readlines()
print(f"You have {len(lines)} items in you bucket list.")
file.close()

file = open('bucket-list.txt', 'a')
file.write("4. Travel to Japan\n")
file.write("5. Run a 5k marathon\n")
file.close()
print("\n More items added!")

file = open("bucket-list.txt", "r")
print("\n=== Updated Bucket List ===")
print(file.read())
file.close()
